### ISSUE TITLE
CREATE: New Project

### ISSUE THREAD

**Issue by LawilliaJPN** [LawilliaJPN/CrossDecagonR#1]
1週間で作ったプロジェクトをベースにアプデしていくのはもう嫌だ

# TODO
- [x] INSTALL: Unity new version
- [x] CREATE: New Project
- [x] CHANGE: Platform to Android
- [x] CLONE: This Repository
