### ISSUE TITLE
ADD: Preload Scene

### ISSUE THREAD

**Issue by LawilliaJPN** [LawilliaJPN/CrossDecagonR#5]
タイトル画面の前に

# TODO
- [ ] ADD: Preload Scene
- [ ] ADD: Title Scene
- [ ] ADD: Register User Name
- [ ] ADD: Load Title Scene
