### ISSUE TITLE
ADD:  Color Scheme Container

### ISSUE THREAD

**Issue by LawilliaJPN** [LawilliaJPN/CrossDecagonR#6]
テーマ（配色等）を管理するための準備

# TODO
- [x] LEARN: ScriptableObject
- [x] ADD: Enum Color Scheme
- [x] ADD: Color Scheme Item
- [x] ADD: Color Scheme (<- ScriptableObject)
- [x] ADD: Color Scheme Data (<- ScriptableObject)

**Comment by LawilliaJPN** [comment]
note https://note.mu/lawilliajpn/n/nd5aed337ab6f
