### ISSUE TITLE
ADD: Color Scheme ScriptableObject

### ISSUE THREAD

**Issue by LawilliaJPN** [LawilliaJPN/CrossDecagonR#7]
既存の配色を ScriptableObject で追加

# TODO
- [ ] ADD: Color Scheme "Cross Decagon" (Light-CH)
- [ ] ADD: Color Scheme "Light" (Light-CD)
- [ ] ADD: Color Scheme "Original" (Original)

**Comment by LawilliaJPN** [comment]
note https://note.mu/lawilliajpn/n/nd5aed337ab6f
